### ISSUE TITLE
Is it possible to run the program mpi_heat2D.c on Linux ALPINE?

### ISSUE THREAD

**Issue by xelaboy** [tzikis/HPerf#1]
Hello. Greetings!

Please, is it possible to run the program mpi_heat2D.c on Linux **ALPINE**?
I'm running the program OK on my machine laptop Ubuntu.
But when trying to run it on Alpine I;m getting the error below.
Please advise. Thanks much in advance!

/project $ mpirun ./mpi_heat2D
Starting mpi_heat2D with 4 worker tasks.
Grid size: X= 20  Y= 20  Time steps= 100
Initializing grid and writing initial.dat file...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 496 RUNNING AT 192.168.208.2
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

**Comment by tzikis** [comment]
Hi there,
I'm afraid I can't help since it's been waaaay too long since I built this and it only ever worked on Ubuntu in the first place, so I wouldn't even know where to start

**Comment by xelaboy** [comment]
Ok. Thanks much anyway!
In fact I've just done it work on an Alpine Docker Container changing the permissions of the files involved and also setting up the $DISPLAY and X11 GUI configs.
Best Regards.

**Comment by xelaboy** [comment]
Ok. Thanks much anyway!
In fact I've just done it work on an Alpine Docker Container changing the permissions of the files involved and also setting up the $DISPLAY and X11 GUI configs.
Best Regards.

Muito Obrigado,
Alex Luz

________________________________
